version: "2"
services:
 otel-collector:
   image: otel/opentelemetry-collector-contrib:0.112.0
   command: ["--config=/etc/otel-collector-config.yaml"]
   volumes:
     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
     - /tmp/test-logs:/etc/test-logs
   ports:
     - "4317:4317"   # OTLP gRPC receiver
     - "4318:4318"   # OTLP HTTP receiver
